# =============================================================================
# 雷达系统配置文件 Radar System Configuration
# =============================================================================

# =============================================================================
# 网络通信配置 Network Communication Configuration
# =============================================================================

[network.ips]
# IP地址配置
DISP_CTRL_IP = "192.168.64.4"        # 显控主机IP地址
DATA_PRO_IP = "192.168.64.3"         # 数据处理主机IP地址
SIG_PRO_IP = "192.168.64.5"          # 信号处理主机IP地址
MONITOR_IP = "192.168.64.6"          # 监控主机IP地址
TAR_CLA_IP = "192.168.64.7"          # 目标分类主机IP地址

[network.ports]
# 端口配置
DISP_2_DATA = 7001                   # 显控->数据处理端口
DISP_2_MONITOR = 7002                # 显控->监控端口
DISP_2_SIG1 = 7003                   # 显控->信号处理端口1
DISP_2_SIG2 = 7004                   # 显控->信号处理端口2
DISP_GET_DATA_PORT = 8001            # 显控接收数据端口
DISP_GET_SIG_PORT1 = 8002            # 显控接收信号端口1
DISP_GET_SIG_PORT2 = 8003            # 显控接收信号端口2
DISP_GET_TARGET_PORT = 8004          # 显控接收目标端口
DISP_GET_MONITOR_PORT = 8005         # 显控接收监控端口
DATA_GET_DISP = 8006                 # 数据处理接收显控端口
DATA_PRO_2_DISP = 8007               # 数据处理->显控端口
SIG_2_DISP_PORT1 = 8008              # 信号处理->显控端口1
SIG_2_DISP_PORT2 = 8009              # 信号处理->显控端口2
MONITOR_GET_DISP_PORT = 8010         # 监控接收显控端口
TAR_2_DISP = 8011                    # 目标分类->显控端口

[network.ids]
# 系统ID配置
DISP_CTRL_ID = 1                     # 显示控制系统ID
DATA_PRO_ID = 2                      # 数据处理系统ID
SIG_PRO_ID = 3                       # 信号处理系统ID
MONITOR_ID = 4                       # 监控系统ID
TAR_CLA_ID = 5                       # 目标分类系统ID

# =============================================================================
# 雷达系统参数配置 Radar System Parameters Configuration
# =============================================================================

[radar]
# 雷达位置配置（基于index.html中的默认值）
longitude = 108.9138                 # 雷达中心经度（西电99号楼）
latitude = 34.2311                   # 雷达中心纬度（西电99号楼）
altitude = 400.0                     # 雷达海拔高度（米）
azimuth = 0.0                        # 阵面指北角（度）
pitch = 0.0                          # 俯仰角（度）
roll = 0.0                           # 横滚角（度）

[polarDisp.range]
# 极坐标显示距离范围配置
min = 1                              # 最小显示距离（公里）
max = 5                              # 最大显示距离（公里，与index.html默认范围一致）

# =============================================================================
# 地图显示配置 Map Display Configuration  
# =============================================================================

[map]
# 地图基本配置
default_type = 1                     # 默认地图类型：0=无地图，1=路网图，2=标准图，3=卫星图

# =============================================================================
# 扇形显示配置 Sector Display Configuration
# =============================================================================

[sectorDisp.angle]
# 扇形角度范围配置（单位：度）
min = -30                            # 默认最小角度
max = 30                             # 默认最大角度

[sectorDisp.range] 
# 扇形距离范围配置（单位：公里）
min = 0                              # 默认最小距离
max = 5                              # 默认最大距离（与全局最大距离一致）

# =============================================================================
# 系统运行配置 System Runtime Configuration
# =============================================================================

[system]
# 系统运行参数
log_level = "INFO"                   # 日志级别：DEBUG/INFO/WARNING/ERROR
auto_save_interval = 300             # 自动保存间隔（秒）