[ui]
dpi_policy = "fixed"
ui_scale = 1.0

[radar]
longitude = 109.123922221
latitude = 34.225249343

[polarDisp.range]
min = 0
max = 5

[marine.network]
local_ip = "192.168.1.100"
echo_port = 9000
servo_ip = "192.168.1.30"
servo_port = 9000
auto_send_ms = 0
fragment_timeout_ms = 500

[marine.control]
cmd_num = 0
azimuth_deg = 0.0
range = 7
gain = 0
interference = 0
level = 0
sea_clutter = 0
rain_clutter = 0
tx_on = false
servo_gear = 0

[marine.display]
echo_decay_ms = 10000
colormap = "simrad"
sweep_history_rounds = 1
echo_debug = false
